spring:
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
  jms:
    template:
      receive-timeout: 3000
bar:
  transport: jms
resilience4j:
  retry:
    instances:
      bar:
        max-attempts: 1
        wait-duration: 200ms
  circuitbreaker:
    instances:
      bar:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s